[[MongoC]]
arch = "aarch64"
git-tree-sha1 = "79e4e134ce4bba765d16c3b3da2a0698ab210756"
os = "macos"

    [[MongoC.download]]
    sha256 = "673fea6028af22c07b18742b71c643f975fcf9c13f8600aff222e8cd81ea45cf"
    url = "https://github.com/JuliaBinaryWrappers/MongoC_jll.jl/releases/download/MongoC-v1.28.1+0/MongoC.v1.28.1.aarch64-apple-darwin.tar.gz"
[[MongoC]]
arch = "aarch64"
git-tree-sha1 = "2edb3cbe345f89511e6224969bbc267048db3971"
libc = "glibc"
os = "linux"

    [[MongoC.download]]
    sha256 = "eb68a6bf733241b6c16ad6138a0f51f0cee375399dae0e5880c900b848cb8006"
    url = "https://github.com/JuliaBinaryWrappers/MongoC_jll.jl/releases/download/MongoC-v1.28.1+0/MongoC.v1.28.1.aarch64-linux-gnu.tar.gz"
[[MongoC]]
arch = "aarch64"
git-tree-sha1 = "30ce899ccf27eb44b6de8dd2e2be2a3ab7eb6ca4"
libc = "musl"
os = "linux"

    [[MongoC.download]]
    sha256 = "cec6d529fe5aff6e2436e323032dd07c5bd9523be0b1187e5119931cfac9010f"
    url = "https://github.com/JuliaBinaryWrappers/MongoC_jll.jl/releases/download/MongoC-v1.28.1+0/MongoC.v1.28.1.aarch64-linux-musl.tar.gz"
[[MongoC]]
arch = "aarch64"
git-tree-sha1 = "afd759ca184e6e77b3e5a3408007d2e5fb9411fb"
os = "freebsd"

    [[MongoC.download]]
    sha256 = "52400b98e42c3a0d238d5a4a2be12b93615a0b670a809397cbf8a05aadcf266a"
    url = "https://github.com/JuliaBinaryWrappers/MongoC_jll.jl/releases/download/MongoC-v1.28.1+0/MongoC.v1.28.1.aarch64-unknown-freebsd.tar.gz"
[[MongoC]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "01655d092a0f7485ef75372693a1774b9ce53094"
libc = "glibc"
os = "linux"

    [[MongoC.download]]
    sha256 = "d360942bb37f6bc7fdf3744379f74c4331d21ff0fee094cfca92c37480f4b6ac"
    url = "https://github.com/JuliaBinaryWrappers/MongoC_jll.jl/releases/download/MongoC-v1.28.1+0/MongoC.v1.28.1.armv6l-linux-gnueabihf.tar.gz"
[[MongoC]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "fff8b462a17b2ea8006c3dc25a9aabb7883b9796"
libc = "musl"
os = "linux"

    [[MongoC.download]]
    sha256 = "b6fadf934b9c5bf15cb55692b47261e55d474f71e9b82c891790fdae89fe58ee"
    url = "https://github.com/JuliaBinaryWrappers/MongoC_jll.jl/releases/download/MongoC-v1.28.1+0/MongoC.v1.28.1.armv6l-linux-musleabihf.tar.gz"
[[MongoC]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d23671d32b88b22b41d2b4394abab62787f9b065"
libc = "glibc"
os = "linux"

    [[MongoC.download]]
    sha256 = "c51be5c16b696d0a5f32b34537da2e467fcdf4d1d922a8c4de02f115c4308a23"
    url = "https://github.com/JuliaBinaryWrappers/MongoC_jll.jl/releases/download/MongoC-v1.28.1+0/MongoC.v1.28.1.armv7l-linux-gnueabihf.tar.gz"
[[MongoC]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d4e10cc4785ad670fa84f870236c8ec3bc1d333a"
libc = "musl"
os = "linux"

    [[MongoC.download]]
    sha256 = "8c1de3c14d0c222b60184d7dcc6200aca861e19fb6e2b0ef860623b23c76c1d6"
    url = "https://github.com/JuliaBinaryWrappers/MongoC_jll.jl/releases/download/MongoC-v1.28.1+0/MongoC.v1.28.1.armv7l-linux-musleabihf.tar.gz"
[[MongoC]]
arch = "i686"
git-tree-sha1 = "e35d031480458ffd5cd562764284a6a5cfcf859b"
libc = "glibc"
os = "linux"

    [[MongoC.download]]
    sha256 = "225ec725d88fb6b3c89fc945aaf7eed822ffc3399bcb61abf340354d9073dd3b"
    url = "https://github.com/JuliaBinaryWrappers/MongoC_jll.jl/releases/download/MongoC-v1.28.1+0/MongoC.v1.28.1.i686-linux-gnu.tar.gz"
[[MongoC]]
arch = "i686"
git-tree-sha1 = "a3d70a14e46a3492ab2f48184e749cd3212b7dc4"
libc = "musl"
os = "linux"

    [[MongoC.download]]
    sha256 = "de938b4e5588d2436244a5d6b938654deb58e86300ff86ed93a67a850770c4a9"
    url = "https://github.com/JuliaBinaryWrappers/MongoC_jll.jl/releases/download/MongoC-v1.28.1+0/MongoC.v1.28.1.i686-linux-musl.tar.gz"
[[MongoC]]
arch = "i686"
git-tree-sha1 = "d7fa8175241115837c181477a225c976143fb3a0"
os = "windows"

    [[MongoC.download]]
    sha256 = "cbda9dd7dabe0da22ad9280f9a4fa46e8e686f26d8fed52086b3160dd0531120"
    url = "https://github.com/JuliaBinaryWrappers/MongoC_jll.jl/releases/download/MongoC-v1.28.1+0/MongoC.v1.28.1.i686-w64-mingw32.tar.gz"
[[MongoC]]
arch = "powerpc64le"
git-tree-sha1 = "41bfd5057a0a628cf40df0b1c2b351cf2387876b"
libc = "glibc"
os = "linux"

    [[MongoC.download]]
    sha256 = "617c33dcb5b28cce19495ce3f4cb42c63e91130ce41e60534c1b2211d344c8a7"
    url = "https://github.com/JuliaBinaryWrappers/MongoC_jll.jl/releases/download/MongoC-v1.28.1+0/MongoC.v1.28.1.powerpc64le-linux-gnu.tar.gz"
[[MongoC]]
arch = "x86_64"
git-tree-sha1 = "f1ddc7b157230f2f92eeed64d1f6bb58516e5770"
os = "macos"

    [[MongoC.download]]
    sha256 = "6d841daf244488475a5fe943148128607409c0092bb7c3cb9c827a6e2304e81e"
    url = "https://github.com/JuliaBinaryWrappers/MongoC_jll.jl/releases/download/MongoC-v1.28.1+0/MongoC.v1.28.1.x86_64-apple-darwin.tar.gz"
[[MongoC]]
arch = "x86_64"
git-tree-sha1 = "ccbf834dee3ed4a30ecdf325bb44fd35c7a379fd"
libc = "glibc"
os = "linux"

    [[MongoC.download]]
    sha256 = "7cd1b08129496daa00b365999462d0a3cec927be77bad794da00984368fb846e"
    url = "https://github.com/JuliaBinaryWrappers/MongoC_jll.jl/releases/download/MongoC-v1.28.1+0/MongoC.v1.28.1.x86_64-linux-gnu.tar.gz"
[[MongoC]]
arch = "x86_64"
git-tree-sha1 = "e44512912d32c824594ce3f3231de0c2090f0346"
libc = "musl"
os = "linux"

    [[MongoC.download]]
    sha256 = "ebf900266846805f5bdf702ab669098474831a73001e5d926854907574bc5fc4"
    url = "https://github.com/JuliaBinaryWrappers/MongoC_jll.jl/releases/download/MongoC-v1.28.1+0/MongoC.v1.28.1.x86_64-linux-musl.tar.gz"
[[MongoC]]
arch = "x86_64"
git-tree-sha1 = "9fc0703c451ebb9fc3fd01d5ac911fbd6f20bb10"
os = "freebsd"

    [[MongoC.download]]
    sha256 = "93eebfcfcf2371836e708ab6525e95220068e3ec9400e5d5877662408181039b"
    url = "https://github.com/JuliaBinaryWrappers/MongoC_jll.jl/releases/download/MongoC-v1.28.1+0/MongoC.v1.28.1.x86_64-unknown-freebsd.tar.gz"
[[MongoC]]
arch = "x86_64"
git-tree-sha1 = "ae9355bc42f3c7d3424dfee44f29f3b96eb6f3ab"
os = "windows"

    [[MongoC.download]]
    sha256 = "da3df6fa5d85f14b0f377a61c67bb64be15b942b2c091d2c5fb0ede9ab30a7f9"
    url = "https://github.com/JuliaBinaryWrappers/MongoC_jll.jl/releases/download/MongoC-v1.28.1+0/MongoC.v1.28.1.x86_64-w64-mingw32.tar.gz"
