[[MongoC]]
arch = "aarch64"
git-tree-sha1 = "2ea3f18277f8d6b82db1ab56cafa44c7f1bfca3f"
os = "macos"

    [[MongoC.download]]
    sha256 = "93ad84a31bb912d7390ee5248df438ec97aa65548c1c634df7aa2e551ee38d3c"
    url = "https://github.com/JuliaBinaryWrappers/MongoC_jll.jl/releases/download/MongoC-v1.25.1+0/MongoC.v1.25.1.aarch64-apple-darwin.tar.gz"
[[MongoC]]
arch = "aarch64"
git-tree-sha1 = "b8ef7cbbc04a03b125e8b3023342b84cd4ea92e3"
libc = "glibc"
os = "linux"

    [[MongoC.download]]
    sha256 = "041c783ccc14416a6533689229171e495ed4bcda995bf718c497f0cabb64f54f"
    url = "https://github.com/JuliaBinaryWrappers/MongoC_jll.jl/releases/download/MongoC-v1.25.1+0/MongoC.v1.25.1.aarch64-linux-gnu.tar.gz"
[[MongoC]]
arch = "aarch64"
git-tree-sha1 = "7bf3860c1a1b7042a7df1e1ce3c2372813d316b2"
libc = "musl"
os = "linux"

    [[MongoC.download]]
    sha256 = "1e534e04c7d02804dbf5af83b7e5c47097f5631099883c93f2c16799774cd7e5"
    url = "https://github.com/JuliaBinaryWrappers/MongoC_jll.jl/releases/download/MongoC-v1.25.1+0/MongoC.v1.25.1.aarch64-linux-musl.tar.gz"
[[MongoC]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3c82e7cb65b75b3203500f01a0400331f042d639"
libc = "glibc"
os = "linux"

    [[MongoC.download]]
    sha256 = "83d32fa046b27cfdcc2f2fe8bd115ad4475999aa09a253bc85c471d343000bc0"
    url = "https://github.com/JuliaBinaryWrappers/MongoC_jll.jl/releases/download/MongoC-v1.25.1+0/MongoC.v1.25.1.armv6l-linux-gnueabihf.tar.gz"
[[MongoC]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ad9abe05ce5e2c280d167b0f7c89ef47d8be991d"
libc = "musl"
os = "linux"

    [[MongoC.download]]
    sha256 = "7303146df12d8a49eaeb86c18eb95168aa62c95b1e8da432bf60b3987e8b1c98"
    url = "https://github.com/JuliaBinaryWrappers/MongoC_jll.jl/releases/download/MongoC-v1.25.1+0/MongoC.v1.25.1.armv6l-linux-musleabihf.tar.gz"
[[MongoC]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6dec1ac2dc0c5f18c61c68741107a4c4ef566085"
libc = "glibc"
os = "linux"

    [[MongoC.download]]
    sha256 = "bd4f570c53003965c4338fdb6119641269aaf9b9c6694ec01f757afe0498356a"
    url = "https://github.com/JuliaBinaryWrappers/MongoC_jll.jl/releases/download/MongoC-v1.25.1+0/MongoC.v1.25.1.armv7l-linux-gnueabihf.tar.gz"
[[MongoC]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a60b9e32fdb065e378229df4d69f9aabbe0e3f43"
libc = "musl"
os = "linux"

    [[MongoC.download]]
    sha256 = "50b3ed6f82b74a4d64666b5c0dfb68e126003aef9b34797fff76e98f727270d6"
    url = "https://github.com/JuliaBinaryWrappers/MongoC_jll.jl/releases/download/MongoC-v1.25.1+0/MongoC.v1.25.1.armv7l-linux-musleabihf.tar.gz"
[[MongoC]]
arch = "i686"
git-tree-sha1 = "bc4c2669fc97934a1a9cf05daeb83be26ea8caef"
libc = "glibc"
os = "linux"

    [[MongoC.download]]
    sha256 = "73cc036ed6e60d9e1cda0b6464b2b8c739b7a9fd62ef0a46f08438ed2b6c15fd"
    url = "https://github.com/JuliaBinaryWrappers/MongoC_jll.jl/releases/download/MongoC-v1.25.1+0/MongoC.v1.25.1.i686-linux-gnu.tar.gz"
[[MongoC]]
arch = "i686"
git-tree-sha1 = "7fce4a3b52b1d748047b1edeee033d32bae03b13"
libc = "musl"
os = "linux"

    [[MongoC.download]]
    sha256 = "92c74db3c400c5784a74bddc65f0c7f39657de91ada979b7f4bc662ffdb8cf8d"
    url = "https://github.com/JuliaBinaryWrappers/MongoC_jll.jl/releases/download/MongoC-v1.25.1+0/MongoC.v1.25.1.i686-linux-musl.tar.gz"
[[MongoC]]
arch = "i686"
git-tree-sha1 = "4cec4d0d159273049e5d9b1ebf3ab57ab8ef362e"
os = "windows"

    [[MongoC.download]]
    sha256 = "d8ec4aa74f316208775f156b15a7542488555682f24a9c032cb995e5135f006a"
    url = "https://github.com/JuliaBinaryWrappers/MongoC_jll.jl/releases/download/MongoC-v1.25.1+0/MongoC.v1.25.1.i686-w64-mingw32.tar.gz"
[[MongoC]]
arch = "powerpc64le"
git-tree-sha1 = "0a9a60c3e06745fed60c133daac95cde5b8f3f66"
libc = "glibc"
os = "linux"

    [[MongoC.download]]
    sha256 = "04b05fe87a2fc739b1fbbad37b78caca2b8b02ae4ac30f2440b164eacff3a66b"
    url = "https://github.com/JuliaBinaryWrappers/MongoC_jll.jl/releases/download/MongoC-v1.25.1+0/MongoC.v1.25.1.powerpc64le-linux-gnu.tar.gz"
[[MongoC]]
arch = "x86_64"
git-tree-sha1 = "398404690c1d9f0b1603fe1fdd886578603edb61"
os = "macos"

    [[MongoC.download]]
    sha256 = "2919b78cb1c324210dab2421c2cfa41efbe9beaa9169daa172c9d2da37d65d96"
    url = "https://github.com/JuliaBinaryWrappers/MongoC_jll.jl/releases/download/MongoC-v1.25.1+0/MongoC.v1.25.1.x86_64-apple-darwin.tar.gz"
[[MongoC]]
arch = "x86_64"
git-tree-sha1 = "b4eaa7bb890b09ed9a8a26c2b79b8603c581c504"
libc = "glibc"
os = "linux"

    [[MongoC.download]]
    sha256 = "2ec083725ab3dbeeb8dbe7e743e3a84138d2e5375c1fe691ba0779418b3007d3"
    url = "https://github.com/JuliaBinaryWrappers/MongoC_jll.jl/releases/download/MongoC-v1.25.1+0/MongoC.v1.25.1.x86_64-linux-gnu.tar.gz"
[[MongoC]]
arch = "x86_64"
git-tree-sha1 = "66b42a7d99f29ec18e78822753867fb0e66fb5d7"
libc = "musl"
os = "linux"

    [[MongoC.download]]
    sha256 = "422fb9993c59af843cb1575c0864587dbde36e86c7a9aa4f074cf29c10bebaf5"
    url = "https://github.com/JuliaBinaryWrappers/MongoC_jll.jl/releases/download/MongoC-v1.25.1+0/MongoC.v1.25.1.x86_64-linux-musl.tar.gz"
[[MongoC]]
arch = "x86_64"
git-tree-sha1 = "55d2558424705094bd540c8d02f47fbeaca55df5"
os = "freebsd"

    [[MongoC.download]]
    sha256 = "a429c9064107f51701c921d3e0b1c042fef8acfaa0ff2934ef98a2e0117c0e21"
    url = "https://github.com/JuliaBinaryWrappers/MongoC_jll.jl/releases/download/MongoC-v1.25.1+0/MongoC.v1.25.1.x86_64-unknown-freebsd.tar.gz"
[[MongoC]]
arch = "x86_64"
git-tree-sha1 = "124015fefff801be55c787a01cd6108d9757c8d3"
os = "windows"

    [[MongoC.download]]
    sha256 = "48d0e23934a3c43c1455382ad72232cc9fe48a1cf5ee370caa0336e29d215760"
    url = "https://github.com/JuliaBinaryWrappers/MongoC_jll.jl/releases/download/MongoC-v1.25.1+0/MongoC.v1.25.1.x86_64-w64-mingw32.tar.gz"
