# Autogenerated wrapper script for MongoC_jll for x86_64-apple-darwin
export libbson, libmongoc

using OpenSSL_jll
using Zlib_jll
using Zstd_jll
using snappy_jll
JLLWrappers.@generate_wrapper_header("MongoC")
JLLWrappers.@declare_library_product(libbson, "@rpath/libbson-1.0.0.dylib")
JLLWrappers.@declare_library_product(libmongoc, "@rpath/libmongoc-1.0.0.dylib")
function __init__()
    JLLWrappers.@generate_init_header(OpenSSL_jll, Zlib_jll, Zstd_jll, snappy_jll)
    JLLWrappers.@init_library_product(
        libbson,
        "lib/libbson-1.0.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmongoc,
        "lib/libmongoc-1.0.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
